FROM python:3.11-slim

WORKDIR /app

COPY requirements-frontend.txt /app/requirements-frontend.txt
RUN pip install --no-cache-dir -r requirements-frontend.txt

COPY frontend.py /app/frontend.py

EXPOSE 8501
# Streamlit inside container must bind to 0.0.0.0
CMD ["streamlit", "run", "frontend.py", "--server.port=8501", "--server.address=0.0.0.0"]
