version: "3.9"

services:
  backend:
    image: bhaskar4297/ai-agent-backend:latest
    container_name: ai-agent-backend
    ports:
      - "9999:9999"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}

  frontend:
    image: ai-agent-frontend:latest
    container_name: ai-agent-frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:9999
    depends_on:
      - backend
